# Generated by Django 4.1.7 on 2023-03-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_isadmin_customer_ismoderator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='stock',
        ),
    ]
