# Generated by Django 4.2 on 2023-04-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='MRP',
        ),
        migrations.AddField(
            model_name='product',
            name='Selling_price',
            field=models.FloatField(default=False),
        ),
    ]
